name: Deploy to VPS

on:
  push:
    branches:
      - master


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Deploy to VPS
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ~/workspace-vue/spotify-clone/
            git pull
            docker-compose down
            docker-compose up -d --build
